#!/usr/bin/env python3
"""Validate lecturer revision No. 3 artifacts."""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
errors: list[str] = []

required = [
    'docs/260602 Paper Hibah-People-Counting-revisi-dari-dosen.pdf',
    'docs/_extracted/revisi-dosen-260602/full_text.txt',
    'docs/revisions/revisi-no3-komentar-dosen.md',
    'docs/revisions/revisi-no3-usulan-pendekatan-copy-to-word.md',
    'docs/revisions/revisi-no3-review-dan-catatan.md',
    'docs/reviews/review-revisi-no3-usulan-pendekatan.md',
    'docs/reviews/review-revisi-no3-usulan-pendekatan-final.md',
    'docs/diagrams/revisi-no3-architecture.png',
    'docs/diagrams/revisi-no3-research-workflow.png',
    'docs/diagrams/revisi-no3-id-state-memory.png',
]

for rel in required:
    if not (ROOT / rel).exists():
        errors.append(f'missing required revision artifact: {rel}')

copy_path = ROOT / 'docs/revisions/revisi-no3-usulan-pendekatan-copy-to-word.md'
if copy_path.exists():
    text = copy_path.read_text(encoding='utf-8', errors='replace')
    required_terms = [
        'Rancangan Eksperimen',
        'Arsitektur Sistem yang Diusulkan',
        'Data Eksperimen dan Preprocessing',
        'Tahapan Pengembangan Sistem',
        'Rancangan ID State Memory',
        'Rencana Skenario Eksperimen',
        'Rencana Diskusi Hasil',
        'Rencana Evaluasi Sistem dan Ancaman terhadap Validitas',
        'Wohlin',
        'YOLO26',
        'YOLOv10',
        'RT-DETR',
        'DiffMOT',
        'OC-SORT',
        'HOTA',
        'IDF1',
        'counting error',
        'Formalisme sederhana',
        '15.000 citra',
        '8.931 frame',
        '105.855 frame',
        'Video target ruang publik',
    ]
    for term in required_terms:
        if term.lower() not in text.lower():
            errors.append(f'copy-ready revision missing concept: {term}')
    for rel in [
        'docs/diagrams/revisi-no3-architecture.png',
        'docs/diagrams/revisi-no3-research-workflow.png',
        'docs/diagrams/revisi-no3-id-state-memory.png',
    ]:
        if rel not in text:
            errors.append(f'copy-ready revision missing image link: {rel}')
    # Citation policy for this lecturer handoff: use author/year with Sxxx codes,
    # not numeric bracket citations, and do not stack S-code citations at paragraph ends.
    if re.search(r'\[\d+\]', text):
        errors.append('copy-ready revision contains numeric bracket citation; use Sxxx code references instead')
    if re.search(r'\[S\d{3}\]\s*,\s*\[S\d{3}\]', text):
        errors.append('copy-ready revision stacks S-code bracket citations; cite sources sentence-by-sentence')
    if 'Daftar Rujukan Ringkas untuk Sitasi Word' in text:
        errors.append('copy-ready revision still contains numeric citation mapping section')
    # Keep visible AI/tool markers out of the copy-ready artifact and linked filenames.
    if re.search(r'(?i)chatgpt|gpt[-_ ]?image|generated by ai|dibuat oleh ai|hermes|tools? ai', text):
        errors.append('copy-ready revision contains AI/tool disclosure text; move it to review notes, not Word copy section')
    # Avoid hard fake-result wording.
    forbidden = [
        r'(?i)hasil\s+(?:eksperimen|pengujian)\s+(?:menunjukkan|membuktikan|memperlihatkan)',
        r'(?i)model\s+yang\s+diusulkan\s+(?:mencapai|menghasilkan)\s+\d',
    ]
    for pat in forbidden:
        if re.search(pat, text):
            errors.append(f'copy-ready revision may claim actual experiment result: {pat}')

comments = ROOT / 'docs/revisions/revisi-no3-komentar-dosen.md'
if comments.exists():
    text = comments.read_text(encoding='utf-8', errors='replace')
    for code in ['DL54', 'DL55', 'DL56', 'DL57', 'DL58']:
        if code not in text:
            errors.append(f'comment mapping missing {code}')

bib = ROOT / 'references/references.bib'
if bib.exists() and 'Wohlin2012Experimentation' not in bib.read_text(encoding='utf-8', errors='replace'):
    errors.append('references.bib missing Wohlin2012Experimentation')

if errors:
    print('REVISION NO3 VALIDATION FAILED')
    for e in errors:
        print('-', e)
    sys.exit(1)

print('REVISION NO3 VALIDATION PASSED')
